name: wikitude_flutter_app
description: A new Flutter project.

version: 9.4.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  location: ^2.3.5
  path_provider: ^1.3.0
  wakelock: ^0.1.3

  augmented_reality_plugin_wikitude:
    path: ./plugin/augmented_reality_plugin_wikitude/

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.1
  json_serializable: ^3.2.3

flutter:

  uses-material-design: true

  assets:
    - samples/
    - samples/x_Demo_3_SolarSystem(2dTracking)/
    - samples/x_Demo_3_SolarSystem(2dTracking)/js/
    - samples/x_Demo_3_SolarSystem(2dTracking)/css/
    - samples/x_Demo_3_SolarSystem(2dTracking)/assets/
    - samples/x_Demo_2_SolarSystem(Geo)/
    - samples/x_Demo_2_SolarSystem(Geo)/js/
    - samples/x_Demo_2_SolarSystem(Geo)/css/
    - samples/x_Demo_2_SolarSystem(Geo)/assets/
    - samples/x_Demo_1_2dTrackingAndGeo/
    - samples/x_Demo_1_2dTrackingAndGeo/js/
    - samples/x_Demo_1_2dTrackingAndGeo/css/
    - samples/x_Demo_1_2dTrackingAndGeo/assets/
    - samples/12_HardwareControl_3_AdvancedFeatures/
    - samples/12_HardwareControl_3_AdvancedFeatures/js/
    - samples/12_HardwareControl_3_AdvancedFeatures/css/
    - samples/12_HardwareControl_3_AdvancedFeatures/assets/
    - samples/12_HardwareControl_3_AdvancedFeatures/jquery/
    - samples/12_HardwareControl_3_AdvancedFeatures/jquery/images/
    - samples/12_HardwareControl_2_CameraSwitching/
    - samples/12_HardwareControl_2_CameraSwitching/js/
    - samples/12_HardwareControl_2_CameraSwitching/css/
    - samples/12_HardwareControl_2_CameraSwitching/assets/
    - samples/12_HardwareControl_2_CameraSwitching/jquery/
    - samples/12_HardwareControl_2_CameraSwitching/jquery/images/
    - samples/12_HardwareControl_1_FrontCamera/
    - samples/12_HardwareControl_1_FrontCamera/js/
    - samples/12_HardwareControl_1_FrontCamera/assets/
    - samples/12_HardwareControl_1_FrontCamera/jquery/
    - samples/12_HardwareControl_1_FrontCamera/jquery/images/
    - samples/11_Video_4_Bonus-TransparentVideo/
    - samples/11_Video_4_Bonus-TransparentVideo/js/
    - samples/11_Video_4_Bonus-TransparentVideo/css/
    - samples/11_Video_4_Bonus-TransparentVideo/assets/
    - samples/11_Video_3_SnappingVideo/
    - samples/11_Video_3_SnappingVideo/js/
    - samples/11_Video_3_SnappingVideo/css/
    - samples/11_Video_3_SnappingVideo/assets/
    - samples/11_Video_2_PlaybackStates/
    - samples/11_Video_2_PlaybackStates/js/
    - samples/11_Video_2_PlaybackStates/css/
    - samples/11_Video_2_PlaybackStates/assets/
    - samples/11_Video_1_SimpleVideo/
    - samples/11_Video_1_SimpleVideo/js/
    - samples/11_Video_1_SimpleVideo/css/
    - samples/11_Video_1_SimpleVideo/assets/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/js/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/css/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/assets/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/jquery/
    - samples/10_BrowsingPois_6_Bonus-CaptureScreen/jquery/images/
    - samples/10_BrowsingPois_5_NativeDetailScreen/
    - samples/10_BrowsingPois_5_NativeDetailScreen/js/
    - samples/10_BrowsingPois_5_NativeDetailScreen/css/
    - samples/10_BrowsingPois_5_NativeDetailScreen/assets/
    - samples/10_BrowsingPois_5_NativeDetailScreen/jquery/
    - samples/10_BrowsingPois_5_NativeDetailScreen/jquery/images/
    - samples/10_BrowsingPois_4_ReloadingContent/
    - samples/10_BrowsingPois_4_ReloadingContent/js/
    - samples/10_BrowsingPois_4_ReloadingContent/css/
    - samples/10_BrowsingPois_4_ReloadingContent/assets/
    - samples/10_BrowsingPois_4_ReloadingContent/jquery/
    - samples/10_BrowsingPois_4_ReloadingContent/jquery/images/
    - samples/10_BrowsingPois_3_LimitingRange/
    - samples/10_BrowsingPois_3_LimitingRange/js/
    - samples/10_BrowsingPois_3_LimitingRange/css/
    - samples/10_BrowsingPois_3_LimitingRange/assets/
    - samples/10_BrowsingPois_3_LimitingRange/jquery/
    - samples/10_BrowsingPois_3_LimitingRange/jquery/images/
    - samples/10_BrowsingPois_2_AddingRadar/
    - samples/10_BrowsingPois_2_AddingRadar/js/
    - samples/10_BrowsingPois_2_AddingRadar/css/
    - samples/10_BrowsingPois_2_AddingRadar/assets/
    - samples/10_BrowsingPois_2_AddingRadar/jquery/
    - samples/10_BrowsingPois_2_AddingRadar/jquery/images/
    - samples/10_BrowsingPois_1_PresentingDetails/
    - samples/10_BrowsingPois_1_PresentingDetails/js/
    - samples/10_BrowsingPois_1_PresentingDetails/assets/
    - samples/10_BrowsingPois_1_PresentingDetails/jquery/
    - samples/10_BrowsingPois_1_PresentingDetails/jquery/images/
    - samples/09_ObtainPoiData_3_FromWebservice/
    - samples/09_ObtainPoiData_3_FromWebservice/js/
    - samples/09_ObtainPoiData_3_FromWebservice/assets/
    - samples/09_ObtainPoiData_3_FromWebservice/jquery/
    - samples/09_ObtainPoiData_3_FromWebservice/jquery/images/
    - samples/09_ObtainPoiData_2_FromLocalResource/
    - samples/09_ObtainPoiData_2_FromLocalResource/js/
    - samples/09_ObtainPoiData_2_FromLocalResource/assets/
    - samples/09_ObtainPoiData_2_FromLocalResource/jquery/
    - samples/09_ObtainPoiData_2_FromLocalResource/jquery/images/
    - samples/09_ObtainPoiData_1_FromApplicationModel/
    - samples/09_ObtainPoiData_1_FromApplicationModel/js/
    - samples/09_ObtainPoiData_1_FromApplicationModel/assets/
    - samples/09_ObtainPoiData_1_FromApplicationModel/jquery/
    - samples/09_ObtainPoiData_1_FromApplicationModel/jquery/images/
    - samples/08_PointOfInterest_4_SelectingPois/
    - samples/08_PointOfInterest_4_SelectingPois/js/
    - samples/08_PointOfInterest_4_SelectingPois/assets/
    - samples/08_PointOfInterest_4_SelectingPois/jquery/
    - samples/08_PointOfInterest_4_SelectingPois/jquery/images/
    - samples/08_PointOfInterest_3_MultiplePois/
    - samples/08_PointOfInterest_3_MultiplePois/js/
    - samples/08_PointOfInterest_3_MultiplePois/assets/
    - samples/08_PointOfInterest_3_MultiplePois/jquery/
    - samples/08_PointOfInterest_3_MultiplePois/jquery/images/
    - samples/08_PointOfInterest_2_PoiWithLabel/
    - samples/08_PointOfInterest_2_PoiWithLabel/js/
    - samples/08_PointOfInterest_2_PoiWithLabel/assets/
    - samples/08_PointOfInterest_2_PoiWithLabel/jquery/
    - samples/08_PointOfInterest_2_PoiWithLabel/jquery/images/
    - samples/08_PointOfInterest_1_PoiAtLocation/
    - samples/08_PointOfInterest_1_PoiAtLocation/js/
    - samples/08_PointOfInterest_1_PoiAtLocation/assets/
    - samples/08_PointOfInterest_1_PoiAtLocation/jquery/
    - samples/08_PointOfInterest_1_PoiAtLocation/jquery/images/
    - samples/07_3dModels_6_3dModelAtGeoLocation/
    - samples/07_3dModels_6_3dModelAtGeoLocation/js/
    - samples/07_3dModels_6_3dModelAtGeoLocation/css/
    - samples/07_3dModels_6_3dModelAtGeoLocation/assets/
    - samples/07_3dModels_5_AnimatedModelParts/
    - samples/07_3dModels_5_AnimatedModelParts/js/
    - samples/07_3dModels_5_AnimatedModelParts/css/
    - samples/07_3dModels_5_AnimatedModelParts/assets/
    - samples/07_3dModels_4_SnapToScreen/
    - samples/07_3dModels_4_SnapToScreen/js/
    - samples/07_3dModels_4_SnapToScreen/css/
    - samples/07_3dModels_4_SnapToScreen/assets/
    - samples/07_3dModels_3_Interactivity/
    - samples/07_3dModels_3_Interactivity/js/
    - samples/07_3dModels_3_Interactivity/css/
    - samples/07_3dModels_3_Interactivity/assets/
    - samples/07_3dModels_2_AppearingAnimation/
    - samples/07_3dModels_2_AppearingAnimation/js/
    - samples/07_3dModels_2_AppearingAnimation/css/
    - samples/07_3dModels_2_AppearingAnimation/assets/
    - samples/07_3dModels_1_3dModelOnTarget/
    - samples/07_3dModels_1_3dModelOnTarget/js/
    - samples/07_3dModels_1_3dModelOnTarget/css/
    - samples/07_3dModels_1_3dModelOnTarget/assets/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/js/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/css/
    - samples/06_ObjectTracking_4_ExtendedObjectTracking/assets/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/js/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/css/
    - samples/06_ObjectTracking_3_Animated3dAugmentations/assets/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/js/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/css/
    - samples/06_ObjectTracking_2_2dImageAndSoundAugmentations/assets/
    - samples/06_ObjectTracking_1_BasicObjectTracking/
    - samples/06_ObjectTracking_1_BasicObjectTracking/js/
    - samples/06_ObjectTracking_1_BasicObjectTracking/css/
    - samples/06_ObjectTracking_1_BasicObjectTracking/assets/
    - samples/05_InstantTracking_6_LoadInstantTarget/
    - samples/05_InstantTracking_6_LoadInstantTarget/js/
    - samples/05_InstantTracking_6_LoadInstantTarget/css/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/models/
    - samples/05_InstantTracking_6_LoadInstantTarget/assets/buttons/
    - samples/05_InstantTracking_6_LoadInstantTarget/jquery/
    - samples/05_InstantTracking_6_LoadInstantTarget/jquery/images/
    - samples/05_InstantTracking_5_SaveInstantTarget/
    - samples/05_InstantTracking_5_SaveInstantTarget/js/
    - samples/05_InstantTracking_5_SaveInstantTarget/css/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/models/
    - samples/05_InstantTracking_5_SaveInstantTarget/assets/buttons/
    - samples/05_InstantTracking_5_SaveInstantTarget/jquery/
    - samples/05_InstantTracking_5_SaveInstantTarget/jquery/images/
    - samples/05_InstantTracking_4_SceneInteraction/
    - samples/05_InstantTracking_4_SceneInteraction/js/
    - samples/05_InstantTracking_4_SceneInteraction/css/
    - samples/05_InstantTracking_4_SceneInteraction/assets/
    - samples/05_InstantTracking_4_SceneInteraction/assets/models/
    - samples/05_InstantTracking_4_SceneInteraction/assets/buttons/
    - samples/05_InstantTracking_4_SceneInteraction/jquery/
    - samples/05_InstantTracking_4_SceneInteraction/jquery/images/
    - samples/05_InstantTracking_3_Interactivity/
    - samples/05_InstantTracking_3_Interactivity/js/
    - samples/05_InstantTracking_3_Interactivity/css/
    - samples/05_InstantTracking_3_Interactivity/assets/
    - samples/05_InstantTracking_3_Interactivity/assets/models/
    - samples/05_InstantTracking_3_Interactivity/assets/buttons/
    - samples/05_InstantTracking_3_Interactivity/jquery/
    - samples/05_InstantTracking_3_Interactivity/jquery/images/
    - samples/05_InstantTracking_2_3dModelOnPlane/
    - samples/05_InstantTracking_2_3dModelOnPlane/js/
    - samples/05_InstantTracking_2_3dModelOnPlane/css/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/models/
    - samples/05_InstantTracking_2_3dModelOnPlane/assets/buttons/
    - samples/05_InstantTracking_2_3dModelOnPlane/jquery/
    - samples/05_InstantTracking_2_3dModelOnPlane/jquery/images/
    - samples/05_InstantTracking_1_SimpleInstantTracking/
    - samples/05_InstantTracking_1_SimpleInstantTracking/js/
    - samples/05_InstantTracking_1_SimpleInstantTracking/css/
    - samples/05_InstantTracking_1_SimpleInstantTracking/assets/
    - samples/05_InstantTracking_1_SimpleInstantTracking/assets/buttons/
    - samples/05_InstantTracking_1_SimpleInstantTracking/jquery/
    - samples/05_InstantTracking_1_SimpleInstantTracking/jquery/images/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/js/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/css/
    - samples/04_CloudRecognition_3_UsingMetainformationInTheResponse/assets/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/js/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/css/
    - samples/04_CloudRecognition_2_ContinuousImageRecognition/assets/
    - samples/04_CloudRecognition_1_SingleImageRecognition/
    - samples/04_CloudRecognition_1_SingleImageRecognition/js/
    - samples/04_CloudRecognition_1_SingleImageRecognition/css/
    - samples/04_CloudRecognition_1_SingleImageRecognition/assets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/js/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/css/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/assets/
    - samples/03_MultipleTargets_3_TransformationBetweenTargets/assets/models/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/js/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/css/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/assets/
    - samples/03_MultipleTargets_2_DistanceBetweenTargets/assets/models/
    - samples/03_MultipleTargets_1_MultipleTargets/
    - samples/03_MultipleTargets_1_MultipleTargets/js/
    - samples/03_MultipleTargets_1_MultipleTargets/css/
    - samples/03_MultipleTargets_1_MultipleTargets/assets/
    - samples/03_MultipleTargets_1_MultipleTargets/assets/models/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/js/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/css/
    - samples/02_AdvancedImageTracking_3_ExtendedTracking/assets/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/js/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/css/
    - samples/02_AdvancedImageTracking_2_DistanceToTarget/assets/
    - samples/02_AdvancedImageTracking_1_Gestures/
    - samples/02_AdvancedImageTracking_1_Gestures/js/
    - samples/02_AdvancedImageTracking_1_Gestures/css/
    - samples/02_AdvancedImageTracking_1_Gestures/assets/
    - samples/02_AdvancedImageTracking_1_Gestures/jquery/
    - samples/02_AdvancedImageTracking_1_Gestures/jquery/images/
    - samples/01_ImageTracking_5_Bonus-Sparkles/
    - samples/01_ImageTracking_5_Bonus-Sparkles/js/
    - samples/01_ImageTracking_5_Bonus-Sparkles/css/
    - samples/01_ImageTracking_5_Bonus-Sparkles/assets/
    - samples/01_ImageTracking_4_HtmlDrawable/
    - samples/01_ImageTracking_4_HtmlDrawable/js/
    - samples/01_ImageTracking_4_HtmlDrawable/css/
    - samples/01_ImageTracking_4_HtmlDrawable/assets/
    - samples/01_ImageTracking_3_Interactivity/
    - samples/01_ImageTracking_3_Interactivity/js/
    - samples/01_ImageTracking_3_Interactivity/css/
    - samples/01_ImageTracking_3_Interactivity/assets/
    - samples/01_ImageTracking_2_DifferentTargets/
    - samples/01_ImageTracking_2_DifferentTargets/js/
    - samples/01_ImageTracking_2_DifferentTargets/css/
    - samples/01_ImageTracking_2_DifferentTargets/assets/
    - samples/01_ImageTracking_1_ImageOnTarget/
    - samples/01_ImageTracking_1_ImageOnTarget/js/
    - samples/01_ImageTracking_1_ImageOnTarget/css/
    - samples/01_ImageTracking_1_ImageOnTarget/assets/
